---

- name: recovery fstab
  replace:
    path: /etc/fstab
    regexp: "^#\\s(.*\\sswap\\s.*)$"
    replace: "\\1"
  ignore_errors: True

- name: swapoff
  shell: "swapoff -a"
  when:
    - SWITCH_SWAP is defined
    - SWITCH_SWAP == true
  ignore_errors: True

- name: config fstab
  replace:
    path: /etc/fstab
    regexp: "^([^#\\n]*\\sswap\\s.*)$"
    replace: "# \\1"
  when:
    - SWITCH_SWAP is defined
    - SWITCH_SWAP == true
  ignore_errors: True

- name: recovery swapoff
  replace:
    path: /etc/fstab
    regexp: "^#\\s(.*\\sswap\\s.*)$"
    replace: "\\1"
  when:
    - SWITCH_SWAP is defined
    - SWITCH_SWAP != true
  ignore_errors: True

- name: recovery swapoff
  shell: "swapon -a"
  when:
    - SWITCH_SWAP is defined
    - SWITCH_SWAP != true
  ignore_errors: True