---

- name: Check if kubectl exists
  command: which kubectl
  register: kubectl_exists
  delegate_to: "{{ groups['management_cluster_k8smaster'][0] }}"
  run_once: true
  ignore_errors: yes

- name: delete nodes
  command: kubectl delete bn -n bke-{{ cluster_id_lower }} {{ nodes_string }} --ignore-not-found --wait 300s
  register: cluster_complete
  failed_when: cluster_complete.rc != 0
  delegate_to: "{{ groups['management_cluster_k8smaster'][0] }}"
  run_once: true
  ignore_errors: yes  # 退库失败的校验放在后面
  when: kubectl_exists.rc == 0

- name: Check if the work cluster update is complete
  command: kubectl wait --for=jsonpath='{.status.clusterStatus}'=Ready bc/{{ cluster_id_lower }} -n bke-{{ cluster_id_lower }} --timeout="{{ (300 + ((nodes_length | int - 20) * 60 if nodes_length | int > 20 else 0)) }}"s
  register: cluster_complete
  delegate_to: "{{ groups['management_cluster_k8smaster'][0] }}"
  run_once: true
  ignore_errors: yes
  failed_when: cluster_complete.rc != 0
  when: kubectl_exists.rc == 0

- name:  Check if all nodes are deleted
  shell: |
    set -ex
    # 节点删除需要时间,默认5分钟，超过10个节点，每台宿主机多等待60s
    sleep {{ 300 if (nodes_length | int < 10) else (300 + (nodes_length - 10) * 60) | int }}
    # 使用 timeout 限制检查时间
    if ! timeout {{ 1800 if (nodes_length | int < 20) else (1800 + (nodes_length - 20) * 5) | int }} bash -c '
      while kubectl get node "{{ nodes_string }}" --ignore-not-found 2>/dev/null | grep -q .; do
        echo "Waiting for nodes to be deleted...";
        sleep 5;
      done
    '; then
      echo "Timeout reached! Check remaining nodes manually:"
      kubectl get node "{{ nodes_string }}" --ignore-not-found
      exit 1
    fi
    set +ex
    echo "All nodes deleted successfully."
  register: node_complete
  run_once: true
  ignore_errors: yes
  failed_when: node_complete.rc != 0
  when: kubectl_exists.rc == 0

- import_tasks: roles/bke-common/tasks/bke_reset.yml