---
- name: Write autoscaling RBAC
  ansible.builtin.template:
    src: autoscale-role.yaml.j2
    dest: /approot1/paas/kube/conf/autoscale-role.yaml
    owner: kube
    group: users
    mode: '0644'

- name: Apply autoscaling RBAC
  ansible.builtin.command:
    argv: [/approot1/paas/kube/bin/kubectl, --kubeconfig=/approot1/paas/kube/cert/kubectl.kubeconfig, apply, -f, /approot1/paas/kube/conf/autoscale-role.yaml]
  changed_when: true

