---
- name: Install kube-apiserver service unit
  ansible.builtin.copy:
    src: kube-apiserver.service
    dest: /usr/lib/systemd/system/kube-apiserver.service
    owner: root
    group: users
    mode: '0644'
    backup: true
  notify: systemctl daemon-reload

- name: Write kube-apiserver parameters
  ansible.builtin.template:
    src: apiserver.j2
    dest: /approot1/paas/kube/conf/apiserver
    owner: kube
    group: users
    mode: '0644'

- name: Enable and start kube-apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    enabled: true
    state: started
    daemon_reload: true

