---

- name: fetch kubectl's kubeconfig from master
  tags:
    - install
    - check
    - update
  fetch:
    src: /approot1/paas/kube/cert/kubectl.kubeconfig
    dest: /approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/
    flat: yes

- name: restrict fetched kubectl kubeconfig on controller
  tags:
    - install
    - check
    - update
  file:
    path: /approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/kubectl.kubeconfig
    state: file
    owner: "{{ ANSIBLE_USER }}"
    mode: "u=rw,g=,o="
  delegate_to: localhost
  no_log: true
  
- name: fetch kube-proxy's kubeconfig from master
  tags:
    - install
    - check
    - update
  fetch:
    src: /approot1/paas/kube/cert/kube-proxy.kubeconfig
    dest: /approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/
    flat: yes

- name: restrict fetched kube-proxy kubeconfig on controller
  tags:
    - install
    - check
    - update
  file:
    path: /approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/kube-proxy.kubeconfig
    state: file
    owner: "{{ ANSIBLE_USER }}"
    mode: "u=rw,g=,o="
  delegate_to: localhost
  no_log: true
