---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: copy sh
  tags:
    - install
    - check
    - update
  template: src=bootstrap-kubeconfig.sh.j2 dest=/approot1/paas/kube/bin/bootstrap-kubeconfig-{{ inventory_hostname }}.sh owner=kube mode="u=rwx,g=rx,o=rx"
  
- name: boot kubeconfig
  tags:
    - install
    - check
    - update
  shell: "/approot1/paas/kube/bin/bootstrap-kubeconfig-{{ inventory_hostname }}.sh"

- name: restrict generated kubelet bootstrap kubeconfig on master
  tags:
    - install
    - check
    - update
  file:
    path: /approot1/paas/kube/cert/kubelet-bootstrap-{{ inventory_hostname }}.kubeconfig
    state: file
    owner: kube
    group: users
    mode: "u=rw,g=,o="
  no_log: true
