---

- name: Get running processes list from remote host
  shell: "ps -few | grep node_exporter | awk '{print $2}'"
  register: running_processes
  tags:
    - recovery 
  ignore_errors: yes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"
  tags:
    - recovery
  ignore_errors: yes

- name: remove node-exporter
  tags:
    - recovery
  file: path=/approot1/paas/exporter/ state=absent
  ignore_errors: yes 

- name: <node_exporter>absent the automatic start
  tags:
    - recovery
  lineinfile:
    path: /etc/init.d/after.local
    regexp: 'node_exporter$'
    state: absent
  ignore_errors: yes

- name: mkdir /approot1/paas/exporter/bin
  tags:
    - install
    - check
    - update
  file: path=/approot1/paas/exporter/bin state=directory owner=sysop mode="u=rwx,g=rx,o=rx"
    
- name: <node-exporter>download and unarchive {{ NODE_EXPORTER_MEDPATH_AMD }}
  tags:
    - install
    - update
  unarchive: 
    src: http://{{ IHS_IP }}:{{ IHS_PORT }}/{{ LOCALIZATOIN }}/prometheus/{{ NODE_EXPORTER_MEDPATH_AMD }}
    dest: /approot1/paas/exporter/bin
    copy: no
    extra_opts: ['--strip-components=1']

- name: <daemonset>start node exporter service
  tags:
    - install
    - update
  shell: nohup /approot1/paas/exporter/bin/node_exporter --web.listen-address=":9101" &

- name: wait for node_exporter starting
  tags:
    - install
    - check
    - update
  wait_for: timeout=10

- name: Get running processes list from remote host
  tags:
    - install
    - check
    - update
  shell: "ps -few | grep node_exporter | wc -l"
  register: counts

- name: Report status of node_exporter
  tags:
    - install
    - check
    - update
  fail:
    msg: |
      Service node_exporter is not running.
  when: (counts.stdout|int) <= 1
  
- name: <k8snode nodeexporter>config after.local
  tags:
    - install
    - check
    - update
  file:
    path: /etc/init.d/after.local
    state: touch
    owner: root
    mode: 0775

- name: <node_exporter>config the automatic start for suse
  tags:
    - install
    - check
    - update
  lineinfile:
    path: /etc/init.d/after.local
    line: 'nohup /approot1/paas/exporter/bin/node_exporter --web.listen-address=":9101" &'
