---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: <haproxy>make install dir
  tags:
    - install
    - update
    - check
  file: path=/root/haproxy state=directory mode="u=rwx,g=rx,o=rx"

- name: <haproxy>download and unarchive {{ HAPROXY_MEDPATH }}
  tags:
    - install
    - update
  unarchive: 
    src: http://{{ IHS_IP }}:{{ IHS_PORT }}/{{ HAPROXY_MEDPATH }}
    dest: /root/haproxy
    copy: no
    extra_opts: ['--strip-components=1']

- name: <haproxy>unarchive ssl
  tags:
    - install
    - check
    - update
  unarchive: 
    src:  ssl.tar.gz
    dest: /root/haproxy
    
- name: <haproxy>upload haproxy start script
  tags:
    - install
    - check
    - update
  copy: src=starthaproxy.sh dest=/root/haproxy/starthaproxy.sh owner=root group=users mode="u=rwx,g=rx,o=rx" backup=yes
  
- name: <haproxy>upload haproxy parameter file
  tags:
    - install
    - check
    - update
  template: src=haproxy_k8smaster.cfg.j2 dest=/root/haproxy/conf/haproxy_k8smaster.cfg owner=root group=users mode="u=rw,g=r,o=r"

- name: <haproxy>upload haproxy ssl script of k8smaster haproxy
  tags:
    - install
    - check
    - update
  copy: src=haproxy_k8smaster_ssl.sh dest=/root/haproxy/ssl/haproxy_k8smaster_ssl.sh owner=root group=users mode="u=rwx,g=rx,o=rx"

- name: <haproxy>upload haproxy ssl script of k8smaster haproxy
  tags:
    - install
    - check
    - update
  template: src=kubernetes-csr.json.j2 dest=/root/haproxy/ssl/kubernetes-csr.json owner=root group=users mode="u=rwx,g=rx,o=rx"
  notify: <k8smaster>config ssl of k8smaster haproxy

- name: <haproxy>upload haproxy service file
  tags:
    - install
    - check
    - update
  copy: src=haproxy.service dest=/usr/lib/systemd/system/haproxy.service owner=root group=users mode="u=rw,g=r,o=r" backup=yes
  notify: systemctl daemon-reload
  
- meta: flush_handlers
  
- name: <haproxy>enable haproxy service
  tags:
    - install
    - check
    - update
  service: name=haproxy enabled=yes