---
- name: init authorized_key
  tags:
    - install
    - check
    - update
  authorized_key:
    user: sysop
    key: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
    manage_dir: yes

- import_tasks: install_k8smaster.yml
  tags: ins_k8smaster
- import_tasks: fetch_kubeconfig.yml
  tags: fetch_kubeconfig
  run_once: true
  delegate_to: "{{ groups['k8smaster'][0] }}"
- import_tasks: restart_k8smaster.yml
  tags: res_k8smaster


#后续为master启动后执行
- import_tasks: create_clusterrolebinding.yml
  tags: create_clusterrolebinding
  run_once: true
  delegate_to: "{{ groups['k8smaster'][0] }}"
#安装node的内容
- import_tasks: install_docker.yml
  tags: ins_docker
- import_tasks: install_flannel.yml
  tags: ins_flannel
- import_tasks: init_k8snode_kubconfig.yml
  tags: init_k8snode_kubconfig
  delegate_to: "{{ groups['k8smaster'][0] }}"
- import_tasks: install_k8snode.yml
  tags: ins_k8snode
- import_tasks: restart_k8snode.yml
  tags:
    - res_k8snode
    - install
- import_tasks: label_k8smaster.yml
  tags: label_k8smaster
  delegate_to: "{{ groups['k8smaster'][0] }}"
  run_once: true
- import_tasks: install_coredns.yml
  tags: ins_coredns
  delegate_to: "{{ groups['k8smaster'][0] }}"
  run_once: true
