- name: <k8smaster>upload pprof.sh for pprof
  tags:
    - master_download_pprof
  copy: src=pprof.sh dest=/opt owner=root group=root mode="u=rw,g=r,o=r" backup=yes

- name: get master pprof file 1.17.5
  tags:
    - master_download_pprof
  shell: "chmod +x /opt/pprof.sh &&
          bash /opt/pprof.sh  "
  