---

- name: insatll common chart
  include_tasks: "roles/bke-addon/tasks/install_common.yml"

- name: install StatefulFlatNetworkStrategy special chart
  include_tasks: "roles/bke-addon/tasks/install_StatefulFlatNetworkStrategy.yml"
  when: strategy == 'StatefulFlatNetworkStrategy'

- name: install StatelessPortMappingStrategy special chart
  include_tasks: "roles/bke-addon/tasks/install_StatelessPortMappingStrategy.yml"
  when: strategy == 'StatelessPortMappingStrategy'

- name: install StatelessFlatNetworkStrategy special chart
  include_tasks: "roles/bke-addon/tasks/install_StatelessFlatNetworkStrategy.yml"
  when: strategy == 'StatelessFlatNetworkStrategy'