---

- name: Check if kubectl exists
  command: which kubectl
  register: kubectl_exists
  delegate_to: "{{ groups['bootstrap_host'][0] }}"
  run_once: true
  ignore_errors: yes

- name: Run sub-tasks if kubectl exists
  block:
    - name: check manager cluster
      shell: |
        kubectl get bc  -A -o jsonpath='{.items[*].metadata.name}' \
          |grep -vw '{{ cluster_id_lower }}'
      ignore_errors: yes
      register: cluster_list

    - name: delete manager cluster bn
      shell: |
        kubectl get bn -n 'bke-{{ cluster_id_lower }}' -o jsonpath='{.items[*].metadata.name}' | xargs -d ' ' -I {} \
          kubectl delete bn -n 'bke-{{ cluster_id_lower }}' {} --wait 300s
      when: cluster_list is defined and cluster_list.stdout | length > 0

    - name: delete manager cluster bc
      shell: |
        kubectl get bc -n 'bke-{{ cluster_id_lower }}' -o jsonpath='{.items[*].metadata.name}' | xargs -d ' ' -I {} \
          kubectl delete bc -n 'bke-{{ cluster_id_lower }}' {} --wait 300s
      when: cluster_list is defined and cluster_list.stdout | length > 0

  delegate_to: "{{ groups['bootstrap_host'][0] }}"
  run_once: true
  when: kubectl_exists.rc == 0

- import_tasks: roles/bke-common/tasks/bke_reset.yml