---
# This playbook deploys the whole application stack in this site.

- name: install and configure etcd for certificate
  remote_user: sysop
  hosts: k8setcd

  pre_tasks:
    - import_tasks: preflight_1175.yml
  roles:
    - k8setcd_serverless
