---
# This playbook deploys the whole application stack in this site.

# - name: install and configure etcd
  # remote_user: sysop
  # gather_facts: false
  # hosts: k8smaster

  # roles:
    # - etcd

- name: install and configure k8smaster
  remote_user: sysop
  hosts: k8smaster

  pre_tasks:
    - import_tasks: preflight_1175.yml
    - import_tasks: docker_runtime_preflight.yml
    - import_tasks: varutil.yml
    - import_tasks: vm_check.yml
  roles:
    - k8s1175master
