---

- name: upload sh
  copy:
    src: "{{ playbook_dir }}/roles/k8s1175node/files/vm_check.sh"
    dest: /tmp/vm_check.sh
  when: ENABLE_VM_CHECK
  tags:
    - always

- name: execute
  shell: "sh /tmp/vm_check.sh"
  register: vm_check_result
  when: ENABLE_VM_CHECK
  tags:
    - always

- debug:
    msg: "{{ vm_check_result.stdout }}"
  when: ENABLE_VM_CHECK
  tags:
    - always
