---

- name: init authorized_key
  tags:
    - install
    - check
    - update
  authorized_key:
    user: sysop
    key: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
    manage_dir: yes
    
- import_tasks: install_etcd.yml
  tags: ins_etcd
- import_tasks: restart_etcd.yml
  tags: restart_etcd
