---

- name: Define architecture mapping
  set_fact:
    arch_map:
      x86_64: amd64
      aarch64: arm64

- name: Normalize using map
  set_fact:
    soft_arch: "{{ arch_map.get(ansible_machine, ansible_machine) }}"

- name: check tools
  debug:
    msg: "tools : {{ tools | type_debug }}"

- name: download install tools
  unarchive:
    src: "{{ ENV_FILESTATION_URL }}/{{ item }}.{{ soft_arch }}.tar.gz"
    dest: /usr/bin
    copy: no
    owner: sysop
    mode: 0755
  loop: "{{ tools }}"