---

- name: config pam limit
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: "65536"

- name: add modules
  modprobe:
    name: '{{ item.name }}'
    state: present
  with_items:
    - { name: 'nf_conntrack' }
    - { name: 'br_netfilter' }
    - { name: 'bridge' }

- name: System module auto-loading
  shell: '{{ item.cmd }}'
  with_items:
    - { cmd: 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf' }
    - { cmd: 'echo "nf_conntrack" > /etc/modules-load.d/nf_conntrack.conf' }
    - { cmd: 'echo "bridge" > /etc/modules-load.d/bridge.conf' }

- name: modify kernel parameter for ipv4/ipv6
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
  ignore_errors: yes
  with_items:
    - { key: 'vm.swappiness', value: '0' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'fs.aio-max-nr', value: '1048576' }
    - { key: 'fs.inotify.max_user_instances', value: '16384' }
    - { key: 'net.core.rmem_default', value: '12582912' }
    - { key: 'net.core.wmem_default', value: '12582912' }
    - { key: 'net.core.netdev_max_backlog', value: '9000' }
    - { key: 'net.core.somaxconn', value: '262144' }
    - { key: 'net.ipv4.tcp_keepalive_time', value: '1000' }
    - { key: 'net.ipv4.tcp_keepalive_probes', value: '4' }
    - { key: 'net.ipv4.tcp_keepalive_intvl', value: '20' }
    - { key: 'net.ipv4.tcp_synack_retries', value: '3' }
    - { key: 'net.ipv4.tcp_retries2', value: '6' }
    - { key: 'net.ipv4.tcp_max_syn_backlog', value: '8192' }
    - { key: 'net.ipv4.tcp_fin_timeout', value: '30' }
    - { key: 'kernel.pid_max', value: '655350' }
    - { key: 'net.nf_conntrack_max', value: '4194304' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.xfrm4_gc_thresh', value: '2147483647' }
    - { key: 'net.netfilter.nf_conntrack_max', value: '4194304' }
    - { key: 'net.netfilter.nf_conntrack_buckets', value: '1048576' }
    - { key: 'net.ipv4.ip_local_port_range', value: '{{ NET_IPV4_IP_LOCAL_PORT_RANGE }}' }