---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: <flannel>download and unarchive {{ FLANNEL_MEDPATH_SERVERLESS }}
  tags:
    - install
    - update
  unarchive: 
    src: http://{{ IHS_IP }}:{{ IHS_PORT }}/{{ FLANNEL_MEDPATH_SERVERLESS }}
    dest: /usr/bin
    copy: no

- name: upload certificate key for flanneld.pem
  tags:
    - install
    - check
    - update
  copy: src=/approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/flanneld.pem dest=/approot1/paas/kube/cert/flanneld.pem owner=sysop group=users mode="u=rw,g=r,o=r"

- name: upload certificate key for flanneld-key.pem
  tags:
    - install
    - check
    - update
  copy: src=/approot1/paas/admin/app/ansible/task/cert/{{ CLUSTER_ID }}/flanneld-key.pem dest=/approot1/paas/kube/cert/flanneld-key.pem owner=sysop group=users mode="u=rw,g=r,o=r"
  
- name: <flannel>upload flannel service file
  tags:
    - install
    - check
    - update
  copy: src=flanneld.service dest=/usr/lib/systemd/system/flanneld.service owner=root group=users mode="u=rw,g=r,o=r" backup=yes
  notify: 
    - systemctl daemon-reload
    - <k8snode>restart flanneld
  
- name: <flannel>upload flannel parameter file
  tags:
    - install
    - check
    - update
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld owner=root group=users mode="u=rw,g=r,o=r"
  notify: <k8snode>restart flanneld

- block:
  - name: <flannel>config docker service file -1
    tags:
      - install
      - check
      - update
    lineinfile: dest=/usr/lib/systemd/system/docker.service insertafter='^EnvironmentFile=' line="EnvironmentFile=/run/flannel/subnet.env"
    notify: systemctl daemon-reload
  - name: <flannel>config docker service file -2
    tags:
      - install
      - check
      - update
    replace: dest=/usr/lib/systemd/system/docker.service regexp='\$DOCKER_NETWORK_OPTIONS' replace='--bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}' backup=yes
    notify: systemctl daemon-reload
  - name: <flannel>config docker service file -3
    tags:
      - install
      - check
      - update
    lineinfile: dest=/usr/lib/systemd/system/docker.service regexp='^Requires' line="Requires=containerd.socket flanneld.service"
    notify: systemctl daemon-reload
    
- meta: flush_handlers
  
- name: <flannel>enable flannel service
  tags:
    - install
    - check
    - update
  service: name=flanneld enabled=yes