- name: <k8snode>upload pprof.sh for pprof
  tags:
    - node_download_pprof
  copy: src=pprof.sh dest=/opt owner=root group=root mode="u=rw,g=r,o=r" backup=yes

- name: get node pprof file 1.17.5
  tags:
    - node_download_pprof
  shell: "chmod +x /opt/pprof.sh &&
          bash /opt/pprof.sh"