---
#

# - name: <k8snode>restart flanneld
  # service: name=flanneld state=restarted
  
# - name: <k8snode>restart systemd-journald
  # systemd:
    # name: systemd-journald
    # daemon_reload: yes
    # state: restarted
  # async: 60
  # poll: 5
  
- name: <k8snode>start docker
  tags: install
  systemd:
    name: docker
    daemon_reload: yes
    state: started
  async: 60
  poll: 5

- name: <k8snode>start kubelet
  tags: install
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
  async: 60
  poll: 5

- name: <k8snode>start kube-proxy
  tags: install
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: started
  async: 60
  poll: 5
  
- name: wait for confirm service
  tags: install
  wait_for: timeout=5
  
- name: <k8snode>confirm docker started
  tags: install
  systemd:
    name: docker
    daemon_reload: yes
    state: started
  async: 60
  poll: 5

- name: <k8snode>confirm kubelet started
  tags: install
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
  async: 60
  poll: 5

- name: <k8snode>confirm kube-proxy started
  tags: install
  systemd:
    name: kube-proxy
    daemon_reload: yes
    state: started
  async: 60
  poll: 5
