---
- name: copy pass-docker-password.sh
  copy:
    src: pass-docker-password.sh
    dest: /tmp/pass-docker-password.sh
    mode: '0755'

- name: Ensure credential providers directory exists
  file:
    path: /usr/local/bin/kubelet-credential-providers
    state: directory
    mode: "0500"

- name: Ensure credential providers yaml directory exists
  file:
    path: /etc/icbc
    state: directory
    mode: "0500"

- name: Copy docker-credential-fyhub
  copy:
    src: docker-credential-fyhub
    dest: /usr/local/bin/kubelet-credential-providers/docker-credential-fyhub
    mode: "0500"


- name: Copy image-credential-provider.yaml
  template:
    src: image-credential-provider.yaml.j2
    dest: /etc/icbc/image-credential-provider.yaml
    mode: "0400"


- name: run pass-docker-password.sh
  shell: "bash /tmp/pass-docker-password.sh '{{ ENV_DOCKER_SECRET_USERNAME }}' '{{ ENV_DOCKER_SECRET_PASSWORD }}'"


- name: remove pass-docker-password.sh
  file:
    path: /tmp/pass-docker-password.sh
    state: absent

