---

- import_tasks: roles/bke-cert/tasks/init.yml

- name: fetch admin.conf
  fetch:
    src: '/etc/kubernetes/admin.conf'
    dest: '{{ admin_cert_path }}/{{ certOutputFile }}'
    flat: yes

- name: fetch cert files
  fetch:
    src: '/etc/kubernetes/{{ item }}'
    dest: '{{ admin_cert_path }}/{{ item }}'
    flat: yes
  loop:
    - 'admin.crt'
    - 'admin.key'