#!/bin/bash
export ENV_AMC_USABLITY_ADDR={{ ENV_AMC_USABLITY_ADDR }}
export ENV_AMC_USABLITY_PORT={{ ENV_AMC_USABLITY_PORT }}
export ENV_AMC_MODULECODE=F-PAAS2-ETCD-USABLITY-MONITOR
export ENV_APP_NAME=F-PAAS
