---
- name: Verify blackbox-exporter on k8setcd
  hosts: k8setcd
  gather_facts: false
  become: true
  roles:
    - role: k8s1175_component_verify
      k8s1175_component_task: blackbox-exporter

- name: Verify blackbox-exporter on k8smaster
  hosts: k8smaster
  gather_facts: false
  become: true
  roles:
    - role: k8s1175_component_verify
      k8s1175_component_task: blackbox-exporter

- name: Verify blackbox-exporter on k8snode
  hosts: k8snode
  gather_facts: false
  become: true
  roles:
    - role: k8s1175_component_verify
      k8s1175_component_task: blackbox-exporter
