---
- name: Verify kube-proxy on k8smaster
  hosts: k8smaster
  gather_facts: false
  become: true
  roles:
    - role: k8s1175_component_verify
      k8s1175_component_task: kube-proxy

- name: Verify kube-proxy on k8snode
  hosts: k8snode
  gather_facts: false
  become: true
  roles:
    - role: k8s1175_component_verify
      k8s1175_component_task: kube-proxy
