apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: f-redis
  name: f-redis
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: harbor-secret
  namespace: f-redis
data:
  .dockerconfigjson: {{.dockerconfigjson}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redises.middleware.io
spec:
  group: middleware.io
  names:
    kind: Redis
    listKind: RedisList
    plural: redises
    singular: redis
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Redis is the Schema for the redises API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object.'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents.'
              type: string
            metadata:
              type: object
            spec:
              description: RedisSpec defines the desired state of Redis
              type: object
              properties:
                redisImage:
                  type: string
                resources:
                  description: ResourceRequirements describes the compute resource requirements.
                  type: object
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                          - type: integer
                          - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                pods:
                  description: Number of Redis pods
                  format: int32
                  type: integer
                storageSize:
                  type: string
                storageType:
                  type: string
                tenantDomainName:
                  type: string
                tenantProjectID:
                  type: string
                networkBelong:
                  type: string
              required:
                - redisImage
                - pods
            status:
              description: RedisStatus defines the observed state of Redis
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator
rules:
  - apiGroups:
      - networking.upm.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - middleware.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: f-redis

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-operator
subjects:
  - kind: ServiceAccount
    name: redis-operator
    namespace: f-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis-operator
  name: redis-operator
  namespace: f-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator
  template:
    metadata:
      labels:
        name: redis-operator
    spec:
      containers:
        - command:
            - redis-operator
          env:
            - name: WATCH_NAMESPACE
              value: f-redis,default
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: redis-operator
          image: {{ .repo }}redis-operator:v1.0
          imagePullPolicy: IfNotPresent
          name: redis-operator
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"  # 替换为实际的污点键
          operator: "Exists"
          effect: "NoSchedule"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor-secret
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: redis-operator
      # 添加 nodeSelector 选择 master 节点
      nodeSelector:
        node-role.kubernetes.io/control-plane: "control-plane"
