package domain

import (
	"fmt"
	"regexp"
)

var actionIdentifier = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]*$`)

// ActionTaskPath is generated by the platform, never supplied by an owner.
func ActionTaskPath(action ActionDefinition) (string, error) {
	if action.Kind == ActionCheck {
		if !actionIdentifier.MatchString(action.ID) {
			return "", fmt.Errorf("%w: a check requires a safe immutable action ID", ErrInvalid)
		}
		return "tasks/checks/" + action.ID + ".yml", nil
	}
	switch action.Kind {
	case ActionInstall, ActionConfigure, ActionUpgrade, ActionRollback, ActionUninstall:
		return "tasks/" + string(action.Kind) + ".yml", nil
	default:
		return "", fmt.Errorf("%w: unsupported action kind %q", ErrInvalid, action.Kind)
	}
}

// ValidateActionBindings permits incomplete drafts, but never dangling or
// cross-release references. Complete contracts are required at execution and
// publication boundaries; a standalone check may be tested in an incomplete draft.
func ValidateActionBindings(release ComponentRelease, complete bool) error {
	byID := map[string]ActionDefinition{}
	kinds := map[ActionKind]bool{}
	for _, a := range release.Actions {
		if a.ID == "" || (a.ReleaseID != "" && a.ReleaseID != release.ID) {
			return fmt.Errorf("%w: action identity does not belong to this release", ErrInvalid)
		}
		if _, exists := byID[a.ID]; exists {
			return fmt.Errorf("%w: duplicate action ID %s", ErrInvalid, a.ID)
		}
		if a.Kind != ActionCheck && kinds[a.Kind] {
			return fmt.Errorf("%w: duplicate executable action kind %s", ErrInvalid, a.Kind)
		}
		byID[a.ID], kinds[a.Kind] = a, true
	}
	if complete && (!kinds[ActionInstall] || !kinds[ActionRollback]) {
		return fmt.Errorf("%w: install and rollback actions are required", ErrInvalid)
	}
	for _, a := range release.Actions {
		if a.Kind == ActionCheck {
			if a.PreCheckActionID != "" || a.PostCheckActionID != "" || a.Destructive {
				return fmt.Errorf("%w: check %s cannot bind checks or be destructive", ErrInvalid, a.ID)
			}
			continue
		}
		for _, binding := range []struct{ name, id string }{{"pre", a.PreCheckActionID}, {"post", a.PostCheckActionID}} {
			// Rollback may omit its precheck. An omitted postcheck is resolved
			// from the actual source action when the recovery plan is locked.
			if a.Kind == ActionRollback && binding.id == "" {
				continue
			}
			if binding.id == "" && !complete {
				continue
			}
			check, ok := byID[binding.id]
			if !ok || check.Kind != ActionCheck {
				return fmt.Errorf("%w: %s action %s requires a %s-check from the same release", ErrInvalid, a.Kind, a.ID, binding.name)
			}
		}
	}
	return nil
}

// RollbackPostCheck resolves the default using the action being undone, never
// the latest release or an arbitrary install action. The caller locks this
// identity together with the source parameters and workspace digest.
func RollbackPostCheck(release ComponentRelease, rollback ActionDefinition, sourceActionID string) (ActionDefinition, error) {
	id := rollback.PostCheckActionID
	if id == "" {
		source, ok := release.ActionByID(sourceActionID)
		if !ok || (source.Kind != ActionInstall && source.Kind != ActionUpgrade && source.Kind != ActionConfigure) {
			return ActionDefinition{}, fmt.Errorf("%w: 回滚后检查缺少唯一来源动作，请选择专用回滚后检查", ErrConflict)
		}
		id = source.PreCheckActionID
	}
	check, ok := release.ActionByID(id)
	if !ok || check.Kind != ActionCheck {
		return ActionDefinition{}, fmt.Errorf("%w: 回滚后检查必须引用同版本的检查 YAML", ErrConflict)
	}
	return check, nil
}

func (r ComponentRelease) ActionByID(id string) (ActionDefinition, bool) {
	for _, a := range r.Actions {
		if a.ID == id {
			return a, true
		}
	}
	return ActionDefinition{}, false
}
